name: Deploy master

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pre_job:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ github.token }}
          paths_ignore: '["**/README.md"]'

  main:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    container: platformos/testcafe:3.0.1
    runs-on: ubuntu-latest
    env:
      MPKIT_URL: ${{ secrets.MPKIT_URL_QA }}
      MPKIT_EMAIL: ${{ secrets.MPKIT_EMAIL }}
      MPKIT_TOKEN: ${{ secrets.MPKIT_TOKEN }}
      CI: true
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Build
        shell: sh
        run: |
          npm ci
          npm run build

      - name: Deploy QA
        shell: sh
        run: |
          echo working on ${MPKIT_URL/https:\/\//} - ID: ${TEST_ID}
          set -e
          npm -g install @platformos/pos-cli

          pos-cli data clean --auto-confirm --include-schema
          pos-cli deploy
          pos-cli data import --path=./seed/data.zip --zip

      - name: Run testcafe on QA
        shell: sh
        env:
          MPKIT_URL: ${{ secrets.MPKIT_URL_QA }}
        run: |
          set -e
          npm run test

      - name: Publish test reports
        if: always()
        shell: sh
        run: |
          npm run ci:test:publish

      - name: Deploy LIVE
        env:
          MPKIT_URL: ${{ secrets.MPKIT_URL_LIVE }}
        shell: sh
        run: |
          pos-cli deploy
